### ISSUE TITLE
Production /dist/index.js has two console.logs which need to be removed.

### ISSUE THREAD

**Issue by gbuilt** [pureth/react-base64-downloader#9]
This is a really great little component you have here. Thank you for making it and sharing it.

I wanted to let you know that there are two console.logs that were left in the production minified /dist/index.js file that are fairly annoying to have dangling around. 

Right near the end of the file, there's a 

`console.log(t)`

and a 

`console.log(a)`

I didn't see either of these in the /src/ files.

Please remove these when you get a chance. 

Thanks!

**Comment by jowo-io** [comment]
Hi @gbuilt thanks for pointing this out, and thanks for the issue report.
I've only just seen this issue, looks like my notifications aren't setup correctly. I'll get a fix out today.

**Comment by jowo-io** [comment]
Just investigated and cannot locate the console logs in question. See screenshots attached. Only 3 references to `console` made in the `dist/index.js`.

I also had a look in all the old versions of the dist file and a could not locate them.

![Screenshot (307)](https://user-images.githubusercontent.com/12846819/172406395-1d01f586-4cec-4419-a979-28ab01ed2ffa.png)
![Screenshot (308)](https://user-images.githubusercontent.com/12846819/172406406-e1fd015d-004d-4a50-a985-978a0b2de640.png)
![Screenshot (309)](https://user-images.githubusercontent.com/12846819/172406419-5e660809-0a07-48ec-8365-5a0351feff1f.png)
